---
- hosts: 172.31.12.245
  become: yes
  tasks:
   - name: execute linux command directly using playbook
     command: hostname -f
     register: myresult

   - name: display my first task result
     debug: 
       msg: "{{myresult}}"