---
- hosts: 172.31.12.245
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on ansible node
    apt:
     name: apache2
     state: present

  - name: copy my index file into ansible node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html